### ISSUE TITLE
Is there anyway to auto-renew certs?

### ISSUE THREAD

**Issue by humayunghani** [afosto/yaac#12]
Hi,

Is there anyway to renew certs? Like what if I would like to renew stored certs in my DB before 30 days or so? Is there any function call exists for that or should I simply issue fresh new cert again?

Thanks.
Humayun

**Comment by mikemunger** [comment]
As far as I know, one of the changes in lets encrypt v2 api is that there is no renew anymore. The thing to do on renewal is you just go get a new certificate.

https://tools.ietf.org/html/draft-ietf-acme-acme-09
section 7.4.2

" A certificate resource represents a single, immutable certificate.
   If the client wishes to obtain a renewed certificate, the client
   initiates a new order process to request one."

**Comment by humayunghani** [comment]
Ok perfect. Thanks.

**Comment by adamzero1** [comment]
Sorry if this is a dumb question, but does this mean that we need to keep updating our DNS authorization?
When I try to create a new order for the same domain the TXT Record value changes.
I have also tried re-loading the original order by order ID but I just get an error?

**Comment by raicabogdan** [comment]
Yes, that is correct.

**Comment by adamzero1** [comment]
this seems a bit weird, we use certbot dns validation for some bits and it is happy to renew a certificate without updating the DNS validation.

I see the point about the `newOrder` comment on the doc. But there is the contradictory statement
```
The following table illustrates a typical sequence of requests
required to establish a new account with the server, prove control of
an identifier, issue a certificate, and fetch an updated certificate
some time after issuance.
```
Which makes me think it is possible?
Don't get me wrong repo is great, was just hoping I could find the answer and submit a PR for renewal without needing to update the DNS validation all the time.
https://www.rfc-editor.org/rfc/rfc8555#section-6.3
