### ISSUE TITLE
[QUESTION] Revoke a certificate

### ISSUE THREAD

**Issue by hAbd0u** [afosto/yaac#13]
I don't see a method to revoke a certificate, do you plan in near future to support that?

**Comment by bakkerpeter** [comment]
@hAbd0u you are right, there is no support for revocation. Is this blocking you from using this?

**Comment by hAbd0u** [comment]
Yes unfortunately, even I am thinking to make a pull request later when I
find time for that.

**Comment by bakkerpeter** [comment]
Alright, sounds good!
