### ISSUE TITLE
Supply private Key with $client->createOrder();

### ISSUE THREAD

**Issue by ticktoo** [afosto/yaac#17]
Cheers,

we are trying to implement your ACME client within our infrastructure, thanks for your excellent work. I have a question. You expect the private key to be placed in a certain filesystem location. If the client-Class does not find the key, it creates a new one an stores it on your designated fs-location. It is not transparent to me, if my specific key was used to create the CSR or if the class created a new one in a filesystem location, I've probably not expected (within distributed systems).

Why don't you supply a parameter within `$client->createOrder()` or within the constructor to supply the private key? This would seem to me much more straightforward as the private key needs special treatment within automated infrastructures. Also, a `$client->setPrivateKey()` function would be suitable and seems more fail-safe in distributed environments as silently create a new key. Would you accept a pull request or is this utterly out of your scope?

Thank you very much. I appreciate your work.
Sebastian Kraus
ticktoo Systems

**Comment by bakkerpeter** [comment]
Hi Sebastian, thanks for reaching out. I understand your usecase, it is
definitely not out of scope and think we could fix it. I would happilly
review and merge a PR.

Cheers, Peter




Op za 27 jun. 2020 16:25 schreef ticktoo Systems <notifications@github.com>:

**Comment by bakkerpeter** [comment]
Closing for now. If this become urgent again, please go ahead and send in a PR.
