### ISSUE TITLE
Cant Create Wildcard Certificates

### ISSUE THREAD

**Issue by RohirNaik** [afosto/yaac#23]
No option to create wildcard certificates. This option will be great to go ahead. It throws error

**Comment by bakkerpeter** [comment]
This is already possible. Just use DNS (as this is the only supported
validation flow for wildcard certs by let's encrypt) and request a domain
like so: *.example.com

Cheers

Op ma 20 jul. 2020 21:01 schreef RohirNaik <notifications@github.com>:

**Comment by bakkerpeter** [comment]
Closing for now.
