### ISSUE TITLE
Integrate on a website

### ISSUE THREAD

**Issue by AHMADALISAIM786** [afosto/yaac#25]
Hi i want to integrate this tool on my website with a frontend for the users to generate certificate .can anyone explain the process to me .do i need to upload the whole yaac directory on my website and link it to some page or create a custom php page ?
Any help will be appreciated Thanks

**Comment by bakkerpeter** [comment]
I think you need to further explore both the concepts of ssl certificates and webservers before moving on to applying let's encrypt to your website.
I make this assumption based on my opinion that I think your question overly vague and missing direction. Based on this I think this not the right place to start your journey, you'll need to put some study time in first. 
Good luck!
