### ISSUE TITLE
[QUESTION] How to integrate this on my website?

### ISSUE THREAD

**Issue by Sarveshmrao** [afosto/yaac#26]
I already saw issue #25. I will elaborate on my case. What I want to do is get the info from my user and create a client instance then get the output for DNS validation and display it on my site. Then stop the code there, and when the user puts the DNS records for the domain provided the user has a button (say update DNS status or so) on click Self Test is to be run then once that's done get the certificate using a button (say request SSL cert)  once that's there I just display the keys to the user and save a copy in my webserver. 
So this is basically split into three parts. How can I do this? Can I create client and order again and again?
Any help would be appreciated!!!

**Comment by bakkerpeter** [comment]
Sorry for the delay, I think https://github.com/afosto/yaac/issues/28 could help you a lot. 
I'm trying to find some time to write a simple wiki, but have not made it so far yet.

**Comment by bakkerpeter** [comment]
But it sounds like what you are trying to build is already done by @tipswithpunch. Maybe you could ask him or just use his tool? 
https://punchsalad.com/ssl-certificate-generator/

Closing for now, if you have specific questions please put them under #28
