### ISSUE TITLE
How to renew an existing certificate?

### ISSUE THREAD

**Issue by TheRealMattLear** [afosto/yaac#37]
Hi,

Is there a method to check and renew existing certificates? Is this something that could be achieved in the near future?

**Comment by bakkerpeter** [comment]
Please have a look at https://github.com/afosto/yaac/issues/12
Basically you can just fetch a new cert a few days ahead of the expiry.

**Comment by TheRealMattLear** [comment]
Thanks, I did actually search but completely missed that one! Sorry for time wasting; great job. Simplest project available 👍
