### ISSUE TITLE
Do I need a server?

### ISSUE THREAD

**Issue by yellow1912** [afosto/yaac#38]
Okie, this is a weird question because you clearly stated this lib does not need it. However, as I follow the instruction I keep getting error with selfHttpTest. When I look at the code, I don't see anywhere that a server is setup to listen to the incoming request? Am I missing something here?

**Comment by Z3r0byte** [comment]
Decoupled =/= not needed.

Some other acme clients (like certbot) interact with the webserver (nginx/apache) directly by changing their configuration files (thus they are tightly coupled). This library does not do it that way, though depending on the verification method, you will still need a webserver which can serve the validation file. Also keep in mind that this is a PHP library and as such it is meant for use in (web) applications, and not a standalone client. Hope this helps you

**Comment by bakkerpeter** [comment]
Thanks @Z3r0byte for taking the time to explain this so clearly. Closing for now.
