### ISSUE TITLE
Laravel version: 8.20.1 : Installation failed

### ISSUE THREAD

**Issue by uenucom** [afosto/yaac#43]
Laravel version: 8.20.1

composer  require afosto/yaac

Installation failed

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - afosto/yaac[v1.2.0, ..., v1.2.3] require guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires afosto/yaac ^1.2 -> satisfiable by afosto/yaac[v1.2.0, 1.2.1, 1.2.2, v1.2.3].

**Comment by bakkerpeter** [comment]
should be fixed with https://github.com/afosto/yaac/pull/40
thanks @gpibarra
