### ISSUE TITLE
Unable to serialize Authorizations

### ISSUE THREAD

**Issue by mrspence** [afosto/yaac#47]
I need to authorize and then generate the LetsEncrypt certificate in several separate instances, one after the other.

I.e:

1. Setup order
2. Authorization self test
3. Authorization (real)
4. Generate Certificate

To achieve this, I need to serialize authorizations so they can be used by the next PHP instance (job).

However, I'm unable to serialize `Data/Authorization` objects due to the properties within being protected.

What would you suggest? I'm starting a pull request now that I believe fixes this issue... but you might have a solution in mind too! :-)

---

P.S - This is a tidy client compared to others, highly rate! :-)

**Comment by bakkerpeter** [comment]
Closed, see PR #48
