### ISSUE TITLE
Getting Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://acme-v02.api.letsencrypt.org/acme/new-order` resulted in a `400 Bad Request` response:

### ISSUE THREAD

**Issue by adukale** [afosto/yaac#49]
I am getting below error.
Have deployed this on PHP 7.4 CPanel with SSL using: [https://github.com/pompy/yaac-ACME-client-implementation](https://github.com/pompy/yaac-ACME-client-implementation)
Any help would be appreiated.
`[07-Dec-2021 18:36:40 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://acme-v02.api.letsencrypt.org/acme/new-order` resulted in a `400 Bad Request` response:
{
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \ (truncated...)
 in /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/promises/src/TaskQue in /home/bvnqstmw/public_html/ssl/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113`

**Comment by mrspence** [comment]
Do you have a larger error stack? This stack doesn't appear to include afosto/yaac

**Comment by adukale** [comment]
I think the issue was because i was including domain names like these: domain.xyz, www.domain.xyz.
Now that I tried without space, it is working.
Closing the issue. Thanks.
