### ISSUE TITLE
Certificates renewal

### ISSUE THREAD

**Issue by jdbravo** [afosto/yaac#52]
Hi,

I really like how this project was built and the documentation is very clear compared to other clients.

But I wasn't able to find how can I renew all my certificates. May you please let me know how to do that?

Thank you!

**Comment by nhshofficial** [comment]
There is no such thing in API v2. please check previous issues before creating new one. you might find the info. #12

**Comment by bakkerpeter** [comment]
Thanks @nhshofficial.
