### ISSUE TITLE
Not valid certificate

### ISSUE THREAD

**Issue by useapp** [afosto/yaac#53]
This certificate cannot be verified up to trusted certification authority
Issued by: Artificial Apricot R3

**Comment by BastelPichi** [comment]
Hello,
this is the staging mode certificate:
[https://github.com/afosto/yaac#instantiate-the-client](https://github.com/afosto/yaac#instantiate-the-client)

Change `Client::MODE_STAGING` to `MODE_LIVE`. However in testing, stick with the first option to keep load on LE servers low.
Best regards
