### ISSUE TITLE
Helper.php: explode PHP_EOL on WINDOWS

### ISSUE THREAD

**Issue by JobirYusupov** [afosto/yaac#8]
class TestAcme2Controller extends ZControlCmd
{

    public function file_force_contents( $fullPath, $contents, $flags = 0 ){
        $parts = explode( '/', $fullPath );
        array_pop( $parts );
        $dir = implode( '/', $parts );

        if( !is_dir( $dir ) )
            mkdir( $dir, 0777, true );

        file_put_contents( $fullPath, $contents, $flags );
    }

    public function actionRun()
    {
        //Prepare flysystem
        $adapter = new Local('data');

        $filesystem = new Filesystem($adapter);

        //Construct the client
        $client = new Client([
            'username' => 'jobiryusupov0@gmail.com',
            'fs'       => $filesystem,
            'mode'     => Client::MODE_STAGING,
        ]);

        $order = $client->createOrder(['vadeacme.zoft.uz']);

        $authorizations = $client->authorize($order);

        foreach ($authorizations as $authorization) {
            $file = $authorization->getFile();
            file_put_contents($file->getFilename(), $file->getContents());

            $this->file_force_contents( Root.'/execut/web/eyuf/.well-known/acme-challenge/'.$file->getFilename(), $file->getContents(), LOCK_EX );

        }

        if (!$client->selfTest($authorization, Client::VALIDATION_HTTP)) {
            throw new \Exception('Count not verify ownership via HTTP');
        }

        foreach ($authorizations as $authorization) {
            $client->validate($authorization->getHttpChallenge(), 15);
        }

        if ($client->isReady($order)) {
            $certificate = $client->getCertificate($order);  //error here

            file_put_contents('certificate.cert', $certificate->getCertificate());
            $this->file_force_contents( Root.'/execut/web/eyuf/.well-known/acme-challenge/private.key', $certificate->getPrivateKey(), LOCK_EX );
        }

    }
}

error: 
Exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: POST https://acme-staging-v02.api.letsencrypt.org/acme/finalize/13081845/84000364 resulted in a 400 Bad Request response:
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error parsing certificate request: asn1: syntax error:  (truncated...)
'

**Comment by bakkerpeter** [comment]
@JobirYusupov Could you post the full response of the server here?
The snippet suggests that you still have issues with openSSL as I think the CSR is not valid (that is created on the fly).

**Comment by bakkerpeter** [comment]
Closing this, feel free to re-open if you wish to add something.

**Comment by mxprogramer** [comment]
Hi @bakkerpeter, i have found this same error, as you mentioned before the CSR generated is invalid, which is causing the error, but i have configured openSSL correctly and generated a sample CSR from another PHP file. I don't known if it matters but i'm generating a wildcard certificate for both *.domain.com and domain.com so i'm using DNS authorizations.

ERROR CSR generated with yaac:
`-----BEGIN CERTIFICATE REQUEST-----
MIIC9DCCAdwCAQAwga4xCzAJBgNVBAYTAkdCMREwDwYDVQQIDAhTb21lcnNldDEU
MBIGA1UEBwwLR2xhc3RvbmJ1cnkxHzAdBgNVBAoMFlRoZSBCcmFpbiBSb29tIExp
bWl0ZWQxHzAdBgNVBAsMFlBIUCBEb2N1bWVudGF0aW9uIFRlYW0xFDASBgNVBAMM
C1dleiBGdXJsb25nMR4wHAYJKoZIhvcNAQkBFg93ZXpAZXhhbXBsZS5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIQq3s9Szhb63YTMUO9hViT4d3
+n9z3JLq9DGAFfpqkX4NbduTJoEYpO/vNlYhp3Q7ZEoqFB2hdSvd5m1dUL+WVFl3
fAE13Yx1KKTas+why++n8equTTEa2jYWfxiDMseJ7jarnk8nsOVbCz+bYUpOb8NI
CdT1Ays3lJHLzGtSIVi3/33cDZYaSl27RzceGNmhSPYNg98wPxv1kwF4mL5v8lU3
EEfm5fx1TnuGiEh/qcuISlyMLPC9aEbrSOprPXi0eKeRTdbRfty7FyplyDOc1FJ1
YbmBTc+RhyS4a1+1g8oxJE5j6oiqUZhZcT2f+upkOubmUe65Pj/SttKU16snAgMB
AAGgADANBgkqhkiG9w0BAQsFAAOCAQEAwca+mK2LFoTWzB5xJKFG79krwm5O2Mr3
0ShHXyRp70n3u0ROWh1whNl1pY+0lI04rPphcg8m3r8cUwlzPN7ynU4ssWBkYp1u
rGTSCDhBmt9eDuA8RpBT3orUY67rtD6yyO67zBt/rxX2siZN7OdtZ6LFE+YlL6Pn
K/oCTYJm7gj4K4RiWVSeDxGoKB3XlU1x3HbkCdYXmc1OKSCv9o3Zxrl8MdFHhXAf
LuTjeO5crBYPIDsS9pe60R+TX+SkDxrNZgSCtX9cXd/3dDQzz2Et2gZltZrmxW8V
4GpSIePecGp5O`

GOOD CSR generated outside yaac:
`-----BEGIN CERTIFICATE REQUEST-----
MIIC9DCCAdwCAQAwga4xCzAJBgNVBAYTAkdCMREwDwYDVQQIDAhTb21lcnNldDEU
MBIGA1UEBwwLR2xhc3RvbmJ1cnkxHzAdBgNVBAoMFlRoZSBCcmFpbiBSb29tIExp
bWl0ZWQxHzAdBgNVBAsMFlBIUCBEb2N1bWVudGF0aW9uIFRlYW0xFDASBgNVBAMM
C1dleiBGdXJsb25nMR4wHAYJKoZIhvcNAQkBFg93ZXpAZXhhbXBsZS5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9y1dEANYEpE8EwOuuk7Ok+7wB
ND90Ku7CvZ5qFhHJpLEKIlCScxe0K14eHxS1FWceONLQ5QRnf1I3N/u/xmqNNGsY
H8MK8JBEa300k6zSK8N+GIr4r2UaycYxYN7Lu2uXKqidNVXiy7D974SqjwjQWBH8
shvBseLqtnobCJmEanLDSs3LDW/P1cDjIiAGKwL1eZSaav822fPr/j4R93UH4NLW
rOyO6XrABUkNsmij3147oFrQQZOf4qrqX/Xr6FO/9NjZpAOAT28YXQPHsm+SVU7i
Mq8NBywJ467O7Vr8DTzlmdlm9F3xgn69XxHfna1E/CHtZSO4ngT+6BXbsL3vAgMB
AAGgADANBgkqhkiG9w0BAQsFAAOCAQEAlcDVX+XtlE+x6H5D6D9rFCeKCtZGvoPS
CVovdKPkssI9/WIZAgUQBEXVoF+UarDUEy5/JmSRTXBLq5ZazjcELX1O8B+JJC0I
1tepruGI9QOTK3B5IiPM5oSozp/5qk4poQ24GzdpnelGL/gwRN0Do3JpsKvhyNds
I0+G8brlSgLHfdiDJb+xb9q9xN1rWWKt6XGCCopiIFSLJoORyKtDYBPwzkFrGdZ5
XY8sSFxewJIvaPalD3lR45OJyyMoxpn7T4devTGF8FIOGTkFr3YLUk8LOPbHze8+
GZCe+K2QTe26Kw6IQmqaQQ5DBZJFLGxijPQWux5giAPo59QTVyCFig==
-----END CERTIFICATE REQUEST-----`

I appreciate your help

**Comment by mxprogramer** [comment]
I found the solution, error was on toDer function on Helper.php, I'm on windows and this returned an empty string.
Changed line from this:
`$lines = explode(PHP_EOL, $pem);`
To this:
`$lines = preg_split('/\r\n|\r|\n/', $pem);`

Now is working as expected

Thanks

**Comment by trusteddigital** [comment]
Just a note to say that I had this exact problem! Thank you @mxprogramer for posting your workaround. I wonder if we could do something to check if windows or not and do an if for future releases. I'll have a think at some point.

**Comment by bakkerpeter** [comment]
Thanks for the update. To my knowledge PHP_EOL was was working the same on
windows as on Linux, therefore I could not comprehend the situation, but it
seems like you have ran into something that is also described here

https://stackoverflow.com/questions/35625268/php-eol-on-windows-and-linux

https://eidson.info/post/php_eol_is_broken

I agree and think we should change this to your suggestion. So maybe just
replace explode(PHP_EOL... with preg_match(...

Could you go ahead and add a PR?

Cheers and thanks for taking to time to point it out!


Op zo 28 jun. 2020 19:29 schreef Matt Moore <notifications@github.com>:

**Comment by bakkerpeter** [comment]
Fixed with https://github.com/afosto/yaac/pull/34
Thanks @gpibarra
